package com.etoak.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2016-09-13T15:39:15.621+08:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://service.etoak.com/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.HelloResponse")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "print", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.Print")
    @WebMethod
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.PrintResponse")
    public void print();
}
