package com.etoak.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T16:58:46.365+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://service.etoak.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.etoak.com/", className = "com.etoak.client.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.etoak.com/", className = "com.etoak.client.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "uesrname", targetNamespace = "")
        java.lang.String uesrname,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
