
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.etoak.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T12:00:08.774+08:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserServiceService",
                      portName = "UserServicePort",
                      targetNamespace = "http://service.etoak.com/",
                      wsdlLocation = "http://localhost:8088/ws/user?wsdl",
                      endpointInterface = "com.etoak.client.UserService")
                      
public class UserServicePortImpl implements UserService {

    private static final Logger LOG = Logger.getLogger(UserServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.etoak.client.UserService#login(java.lang.String uesrname, java.lang.String password)*
     */
    public java.lang.String login(java.lang.String uesrname, java.lang.String password) { 
        LOG.info("Executing operation login");
        System.out.println(uesrname);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
