
package com.etoak.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T12:00:08.758+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class UserService_UserServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.etoak.com/", "UserServiceService");

    private UserService_UserServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserServiceService ss = new UserServiceService(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServicePort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_uesrname = "";
        java.lang.String _login_password = "";
        java.lang.String _login__return = port.login(_login_uesrname, _login_password);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
