
package com.etoak.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T12:00:08.805+08:00
 * Generated source version: 3.1.11
 * 
 */
 
public class UserService_UserServicePort_Server{

    protected UserService_UserServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new UserServicePortImpl();
        String address = "http://localhost:8088/ws/user";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new UserService_UserServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
